<?php
include('app/model/colbon.php');
    $conn = mysql_connect($AppConfig['db']['host'],$AppConfig['db']['user'], $AppConfig['db']['password']); 
	$conn2 = mysql_connect($AppConfig['db2']['host'],$AppConfig['db2']['user'],$AppConfig['db2']['password'], true);
 	
    mysql_select_db($AppConfig['db']['database'], $conn); 
	mysql_select_db($AppConfig['db2']['database'], $conn2);  
 
$Tak=$this->player->playerId;
$GOLDEX=$this->data['gold_num'];
$SilverX=$this->data['silver'];
$emailer=$this->data['email'];
$percent=($AppConfig['Game']['percent']);


require_once( LANG_UI_PATH."plus.php" );
echo "<h1><p><b>";
echo LANGUI_PLUS_T1;
echo " <font color=\"#FF6F0F\">";
echo LANGUI_PLUS_T2;
echo "</font></b></p></h1>\r\n<div id=\"textmenu\">\r\n   <a href=\"plus.php\"";
if ( $this->selectedTabIndex == 0 )
{
    echo " class=\"selected\"";
}
echo ">";
echo LANGUI_PLUS_T3;
echo "</a>\r\n | <a href=\"plus.php?t=1\"";
if ( $this->selectedTabIndex == 1 )
{
    echo " class=\"selected\"";
}
echo ">";
echo LANGUI_PLUS_T4;
echo "</a>\r\n ";



echo "| <a href=\"plus.php?t=2\"";
if ( $this->selectedTabIndex == 2 )
{
    echo " class=\"selected\"";
}
echo ">";
echo LANGUI_PLUS_T5;
echo "</a>\r\n";


echo "| <a href=\"plus.php?t=3\"";
if ( $this->selectedTabIndex == 3 )
{
    echo " class=\"selected\"";
}
echo "> ";
echo LANGUI_PLUS_T47;
echo "</a>\r\n";

echo "| <a href=\"plus.php?t=4\"";
if ( $this->selectedTabIndex == 4 )
{
    echo " class=\"selected\"";
}
echo "> ";
echo LANGUI_PLUS_T48;
echo "</a>\r\n";

echo "| <a href=\"plus.php?t=5\"";
if ( $this->selectedTabIndex == 5 )
{
    echo " class=\"selected\"";
}
echo "> ";
echo LANGUI_PLUS_T49;
echo "</a>\r\n";

echo "| <a href=\"plus.php?t=6\"";
if ( $this->selectedTabIndex == 6 )
{
    echo " class=\"selected\"";
}
echo "> ";
echo LANGUI_PLUS_T66;
echo "</a>\r\n";


echo "</div>\r\n";
if ( $this->selectedTabIndex == 0 )
{
    if ( $this->packageIndex < 0 )
    {
        echo "<div id=\"products\">\r\n\t";
        $_c = 0;
        foreach ( $this->appConfig['plus']['packages'] as $package )
        {
            ++$_c;
            echo "\t<table class=\"product lang_rtl lang_ar\" cellpadding=\"1\" cellspacing=\"1\">\r\n\t\t<thead>\r\n\t\t\t<tr><th>";
            echo $package['name'];
            echo "</th></tr>\r\n\t\t</thead>\r\n        <tbody>\r\n\t\t\t<tr><td class=\"pic\"><a href=\"?id=";
            echo $_c;
            echo "\"><img src=\"assets/default/plus/";
            echo htmlspecialchars( $package['image'] );
            echo "\" style=\"width:100px;height:100px;\" alt=\"";
            echo htmlspecialchars( $package['name'] );
            echo "\"></a></td></tr>\r\n            <tr><td>";
            echo $package['gold'];
            echo "&nbsp;";
            echo LANGUI_PLUS_T6;
            echo "</td></tr>\r\n            <tr><td>";
            echo $package['cost'];
            echo "&nbsp;";
            echo $package['currency'];
            echo "</td></tr>\r\n\t\t\t<tr><td><a href=\"?id=";
            echo $_c;
            echo "\">";
            echo LANGUI_PLUS_T7;
            echo "</a></td></tr>\r\n\t\t</tbody>\r\n\t</table>\r\n\t";
        }
		echo "\t<table class=\"product lang_rtl lang_ar\" cellpadding=\"1\" cellspacing=\"1\">\r\n\t\t<thead>\r\n\t\t\t<tr><th>";
            echo $this->appConfig['plus']['mobile']['name'];
            echo "</th></tr>\r\n\t\t</thead>\r\n        <tbody>\r\n\t\t\t<tr><td class=\"pic\">"; ?>
<!-- paygol script pg script -->
<?php		echo "</td></tr>\r\n            <tr><td>";
            echo $this->appConfig['plus']['mobile']['gold'];
            echo "&nbsp;";
            echo LANGUI_PLUS_T6;
            echo "</td></tr>\r\n            <tr><td>";
            echo $this->appConfig['plus']['mobile']['cost'];
            echo "&nbsp;";
            echo $this->appConfig['plus']['mobile']['currency'];
            echo "</td></tr>\r\n\t\t\t<tr><td>";
            echo "click on the image";
            echo "</td></tr>\r\n\t\t</tbody>\r\n\t</table>\r\n\t";
		
        echo "\t<div class=\"clear\"></div>\r\n</div>\r\n";
    }
    else
    {
        $_c = 0;
        foreach ( $this->appConfig['plus']['payments'] as $paymentKey => $payment )
        {
            ++$_c;
            echo "<table class=\"rate_details lang_rtl lang_ar\" cellpadding=\"1\" cellspacing=\"1\">\r\n    <thead>\r\n        <tr><th colspan=\"2\">";
            echo $_c.". ".$payment['name'];
            echo "</th></tr>\r\n    </thead>\r\n    <tbody>\r\n        <tr>\r\n            <td class=\"pic\">\r\n\t\t\t\t<img src=\"assets/default/plus/";
            echo htmlspecialchars( $this->appConfig['plus']['packages'][$this->packageIndex]['image'] );
            echo "\" style=\"width:100px;height:100px;\" alt=\"";
            echo htmlspecialchars( $this->appConfig['plus']['packages'][$this->packageIndex]['name'] );
            echo "\">\r\n                <div>";
            echo text_period_lang;
            echo ": ";
            echo constant( "payments_".$paymentKey."_period" );
            echo "</div>\r\n            </td>\r\n            <td class=\"desc\">\r\n                ";
			echo constant( "payments_".$paymentKey."_description" );
			echo "<br>\r\n                <a href=\"#\" onclick=\"window. open('payment.php?p=";
			echo $paymentKey;
			echo "&pg=";
			echo $this->packageIndex;
			echo "','tgpay','scrollbars=yes,status=yes,resizable=yes,toolbar=yes,width=800,height=600');return false;\">\r\n";
			echo "<img src=\"assets/default/plus/";
            echo htmlspecialchars( $payment['image'] );
            echo "\"  alt=\"";
            echo htmlspecialchars( $payment['name'] );
            echo "\"></a><br>\r\n            </td>\r\n        </tr>\r\n    </tbody>\r\n</table>\r\n";
        }
    }
}
else if ( $this->selectedTabIndex == 1 )
{
    echo "<table id=\"plus_features\" class=\"features\" cellpadding=\"1\" cellspacing=\"1\">\r\n\t<thead>\r\n\t\t<tr>\r\n\t\t\t<th colspan=\"2\"><p class=\"custDir\">";
    echo LANGUI_PLUS_T8;
    echo "</p></th>\r\n\t\t</tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td colspan=\"2\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th colspan=\"2\">";
    echo LANGUI_PLUS_T9;
    echo "</th>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"preview\"><img class=\"p1\" src=\"assets/x.gif\" alt=\"";
    echo LANGUI_PLUS_T9;
    echo "\" title=\"";
    echo LANGUI_PLUS_T9;
    echo "\"></td>\r\n\t\t\t<td class=\"text\">";
    echo LANGUI_PLUS_T10;
    echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td colspan=\"2\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th colspan=\"2\">";
    echo LANGUI_PLUS_T11;
    echo "</th>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"preview\"><img class=\"xxl_map\" src=\"assets/x.gif\" alt=\"";
    echo LANGUI_PLUS_T11;
    echo "\" title=\"";
    echo LANGUI_PLUS_T11;
    echo "\"></td>\r\n\t\t\t<td class=\"text\">";
    echo LANGUI_PLUS_T12;
    echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td colspan=\"2\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th colspan=\"2\">";
    echo LANGUI_PLUS_T13;
    echo "</th>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"preview\"><img class=\"p7\" src=\"assets/x.gif\" alt=\"";
    echo LANGUI_PLUS_T13;
    echo "\" title=\"";
    echo LANGUI_PLUS_T13;
    echo "\"></td>\r\n\t\t\t<td class=\"text\">";
    echo LANGUI_PLUS_T14;
    echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td colspan=\"2\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th colspan=\"2\">";
    echo LANGUI_PLUS_T15;
    echo "</th>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"preview\"><img class=\"p8\" src=\"assets/x.gif\" alt=\"";
    echo LANGUI_PLUS_T15;
    echo "\" title=\"";
    echo LANGUI_PLUS_T15;
    echo "\"></td>\r\n\t\t\t<td class=\"text\">";
    echo LANGUI_PLUS_T16;
    echo "</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n<table id=\"gold_features\" class=\"features\" cellpadding=\"1\" cellspacing=\"1\">\r\n\t<thead>\r\n\t\t<tr><th colspan=\"2\">";
    echo LANGUI_PLUS_T17;
    echo "</th></tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td colspan=\"2\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th colspan=\"2\">";
    echo LANGUI_PLUS_T18;
    echo "</th>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"preview\"><img class=\"p1_25\" src=\"assets/x.gif\" alt=\"";
    echo LANGUI_PLUS_T18;
    echo "\" title=\"";
    echo LANGUI_PLUS_T18;
    echo "\"></td>\r\n\t\t\t<td class=\"text\">";
    echo LANGUI_PLUS_T19;
    echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td colspan=\"2\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th colspan=\"2\">";
    echo LANGUI_PLUS_T20;
    echo "</th>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"preview\"><img class=\"p2_25\" src=\"assets/x.gif\" alt=\"";
    echo LANGUI_PLUS_T20;
    echo "\" title=\"";
    echo LANGUI_PLUS_T20;
    echo "\"></td>\r\n\t\t\t<td class=\"text\">";
    echo LANGUI_PLUS_T21;
    echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td colspan=\"2\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th colspan=\"2\">";
    echo LANGUI_PLUS_T22;
    echo "</th>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"preview\"><img class=\"p3_25\" src=\"assets/x.gif\" alt=\"";
    echo LANGUI_PLUS_T22;
    echo "\" title=\"";
    echo LANGUI_PLUS_T22;
    echo "\"></td>\r\n\t\t\t<td class=\"text\">";
    echo LANGUI_PLUS_T23;
    echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td colspan=\"2\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th colspan=\"2\">";
    echo LANGUI_PLUS_T24;
    echo "</th>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"preview\"><img class=\"p4_25\" src=\"assets/x.gif\" alt=\"";
    echo LANGUI_PLUS_T24;
    echo "\" title=\"";
    echo LANGUI_PLUS_T24;
    echo "\"></td>\r\n\t\t\t<td class=\"text\">";
    echo LANGUI_PLUS_T25;
    echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td colspan=\"2\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th colspan=\"2\">";
    echo LANGUI_PLUS_T26;
    echo "</th>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"preview\"><img class=\"bau0\" src=\"assets/x.gif\" alt=\"";
    echo LANGUI_PLUS_T26;
    echo "\" title=\"";
    echo LANGUI_PLUS_T26;
    echo "\"></td>\r\n\t\t\t<td class=\"text\">";
    echo LANGUI_PLUS_T27;
    echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td colspan=\"2\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th colspan=\"2\">";
    echo LANGUI_PLUS_T45;
    echo "</th>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"preview\"><img class=\"gid19\" src=\"assets/x.gif\" alt=\"";
    echo LANGUI_PLUS_T45;
    echo "\" title=\"";
    echo LANGUI_PLUS_T45;
    echo "\"></td>\r\n\t\t\t<td class=\"text\">";
    echo LANGUI_PLUS_T46;
    echo "</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td colspan=\"2\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th colspan=\"2\">";
    echo LANGUI_PLUS_T28;
    echo "</th>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"preview\"><img class=\"npc\" src=\"assets/x.gif\" alt=\"";
    echo LANGUI_PLUS_T28;
    echo "\" title=\"";
    echo LANGUI_PLUS_T28;
    echo "\"></td>\r\n\t\t\t<td class=\"text\">";
    echo LANGUI_PLUS_T29;
    echo "</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n";
}
else if ( $this->selectedTabIndex == 2 )
{
    echo "<p>";
    if ( 0 < $this->data['gold_num'] )
    {
        echo LANGUI_PLUS_T30;
        echo " ";
        echo $this->data['gold_num'];
        echo " ";
        echo LANGUI_PLUS_T31;
    }
    else
    {
        echo LANGUI_PLUS_T32;
    }
    echo "</p>\r\n<table class=\"plusFunctions\" cellpadding=\"1\" cellspacing=\"1\">\r\n\t<thead>\r\n\t\t<tr><th colspan=\"5\">";
    echo LANGUI_PLUS_T33;
    echo "</th></tr>\r\n\t\t<tr><td></td><td>";
    echo LANGUI_PLUS_T34;
    echo "</td><td>";
    echo text_period_lang;
    echo "</td><td>";
    echo LANGUI_PLUS_T2;
    echo "</td><td>";
    echo LANGUI_PLUS_T35;
    echo "</td></tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,0);\"><img class=\"help\" src=\"assets/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">\r\n\t\t\t\t<p><b><font color=\"#71D000\"> ";
    echo LANGUI_PLUS_T36;
    echo "  </p><br>\r\n\t\t\t\t";
    echo "<s";
    echo "pan class=\"run\">&nbsp;";
    echo $this->getRemainingPlusTime( 0 );
    echo "</span>\r\n\t\t\t</td>\r\n\t\t\t<td class=\"dur\">";
    echo $this->plusTable[0]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[0]['time']." ".LANGUI_PLUS_T38;
    echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"assets/x.gif\" class=\"gold\" alt=\"";
    echo LANGUI_PLUS_T6;
    echo "\" title=\"";
    echo LANGUI_PLUS_T6;
    echo "\">";
    echo $this->plusTable[0]['cost'];
    echo "</td>\r\n\t\t\t<td class=\"act\">";
    echo $this->getPlusAction( 0 );
    echo "</td>\r\n\t\t</tr>\t\r\n\t\t<tr>\r\n\t\t\t<td colspan=\"5\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t\t\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,1);\"><img class=\"help\" src=\"assets/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">\r\n\t\t\t\t+<b>25</b>% <img class=\"r1\" src=\"assets/x.gif\" alt=\"";
    echo item_title_1;
    echo "\" title=\"";
    echo item_title_1;
    echo "\"> ";
    echo LANGUI_PLUS_T39;
    echo "<br>\r\n\t\t\t\t";
    echo "<s";
    echo "pan class=\"run\">&nbsp;";
    echo $this->getRemainingPlusTime( 1 );
    echo "</span>\r\n\t\t\t</td>\r\n\t\t\t<td class=\"dur\">";
    echo $this->plusTable[1]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[1]['time']." ".LANGUI_PLUS_T38;
    echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"assets/x.gif\" class=\"gold\" alt=\"";
    echo LANGUI_PLUS_T6;
    echo "\" title=\"";
    echo LANGUI_PLUS_T6;
    echo "\">";
    echo $this->plusTable[1]['cost'];
    echo "</td>\r\n\t\t\t<td class=\"act\">";
    echo $this->getPlusAction( 1 );
    echo "</td>\r\n\t\t</tr>\r\n\t\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,2);\"><img class=\"help\" src=\"assets/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">\r\n\t\t\t\t+<b>25</b>% <img class=\"r2\" src=\"assets/x.gif\" alt=\"";
    echo item_title_2;
    echo "\" title=\"";
    echo item_title_2;
    echo "\"> ";
    echo LANGUI_PLUS_T40;
    echo "<br>\r\n\t\t\t\t";
    echo "<s";
    echo "pan class=\"run\">&nbsp;";
    echo $this->getRemainingPlusTime( 2 );
    echo "</span>\r\n\t\t\t</td>\r\n\t\t\t<td class=\"dur\">";
    echo $this->plusTable[2]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[2]['time']." ".LANGUI_PLUS_T38;
    echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"assets/x.gif\" class=\"gold\" alt=\"";
    echo LANGUI_PLUS_T6;
    echo "\" title=\"";
    echo LANGUI_PLUS_T6;
    echo "\">";
    echo $this->plusTable[2]['cost'];
    echo "</td>\r\n\t\t\t<td class=\"act\">";
    echo $this->getPlusAction( 2 );
    echo "</td>\r\n\t\t</tr>\r\n\t\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,3);\"><img class=\"help\" src=\"assets/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">\r\n\t\t\t\t+<b>25</b>% <img class=\"r3\" src=\"assets/x.gif\" alt=\"";
    echo item_title_3;
    echo "\" title=\"";
    echo item_title_3;
    echo "\"> ";
    echo LANGUI_PLUS_T41;
    echo "<br>\r\n\t\t\t\t";
    echo "<s";
    echo "pan class=\"run\">&nbsp;";
    echo $this->getRemainingPlusTime( 3 );
    echo "</span>\r\n\t\t\t</td>\r\n\t\t\t<td class=\"dur\">";
    echo $this->plusTable[3]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[3]['time']." ".LANGUI_PLUS_T38;
    echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"assets/x.gif\" class=\"gold\" alt=\"";
    echo LANGUI_PLUS_T6;
    echo "\" title=\"";
    echo LANGUI_PLUS_T6;
    echo "\">";
    echo $this->plusTable[3]['cost'];
    echo "</td>\r\n\t\t\t<td class=\"act\">";
    echo $this->getPlusAction( 3 );
    echo "</td>\r\n\t\t</tr>\r\n\t\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,4);\"><img class=\"help\" src=\"assets/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">\r\n\t\t\t\t+<b>25</b>% <img class=\"r4\" src=\"assets/x.gif\" alt=\"";
    echo item_title_4;
    echo "\" title=\"";
    echo item_title_4;
    echo "\"> ";
    echo LANGUI_PLUS_T42;
    echo "<br>\r\n\t\t\t\t";
    echo "<s";
    echo "pan class=\"run\">&nbsp;";
    echo $this->getRemainingPlusTime( 4 );
    echo "</span>\r\n\t\t\t</td>\r\n\t\t\t<td class=\"dur\">";
    echo $this->plusTable[4]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[4]['time']." ".LANGUI_PLUS_T38;
    echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"assets/x.gif\" class=\"gold\" alt=\"";
    echo LANGUI_PLUS_T6;
    echo "\" title=\"";
    echo LANGUI_PLUS_T6;
    echo "\">";
    echo $this->plusTable[4]['cost'];
    echo "</td>\r\n\t\t\t<td class=\"act\">";
    echo $this->getPlusAction( 4 );
    echo "</td>\r\n\t\t</tr>\r\n\t\r\n\t\t<tr>\r\n\t\t\t<td colspan=\"5\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,5);\"><img class=\"help\" src=\"assets/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">";
    echo LANGUI_PLUS_T43;
    echo "</td>\r\n\t\t\t<td class=\"dur\">";
    echo $this->plusTable[5]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[5]['time']." ".LANGUI_PLUS_T38;
    echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"assets/x.gif\" class=\"gold\" alt=\"";
    echo LANGUI_PLUS_T6;
    echo "\" title=\"";
    echo LANGUI_PLUS_T6;
    echo "\">";
    echo $this->plusTable[5]['cost'];
    echo "</td>\r\n\t\t\t<td class=\"act\">";
    echo $this->getPlusAction( 5 );
    echo "</td>\r\n\t\t</tr>\t\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,8);\"><img class=\"help\" src=\"assets/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">";
    echo LANGUI_PLUS_T45;
    echo "</td>\r\n\t\t\t<td class=\"dur\">";
    echo $this->plusTable[7]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[7]['time']." ".LANGUI_PLUS_T38;
    echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"assets/x.gif\" class=\"gold\" alt=\"";
    echo LANGUI_PLUS_T6;
    echo "\" title=\"";
    echo LANGUI_PLUS_T6;
    echo "\">";
    echo $this->plusTable[7]['cost'];
    echo "</td>\r\n\t\t\t<td class=\"act\">";
    echo $this->getPlusAction( 7 );
    echo "</td>\r\n\t\t</tr>\t\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,7);\"><img class=\"help\" src=\"assets/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">";
    echo LANGUI_PLUS_T44;
    echo "</td>\r\n\t\t\t<td class=\"dur\">";
    echo $this->plusTable[6]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[6]['time']." ".LANGUI_PLUS_T38;
    echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"assets/x.gif\" class=\"gold\" alt=\"";
    echo LANGUI_PLUS_T6;
    echo "\" title=\"";
    echo LANGUI_PLUS_T6;
    echo "\">";
    echo $this->plusTable[6]['cost'];
    echo "</td>\r\n\t\t\t<td class=\"act\">";
     echo $this->getPlusAction( 6 );
    //// sssss
    echo "</td>";
    echo "\r\n\t\t</tr>\t\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,8);\"><img class=\"help\" src=\"assets/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">";
    echo CLUB;
    echo "</td>\r\n\t\t\t<td class=\"dur\">";
    echo $this->plusTable[8]['time'] == 0 ? GOLD_FOR_EVER : $this->plusTable[8]['time']." ".LANGUI_PLUS_T38;
    echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"assets/x.gif\" class=\"gold\" alt=\"";
    echo LANGUI_PLUS_T6;
    echo "\" title=\"";
    echo LANGUI_PLUS_T6;
    echo "\">";
    echo $this->plusTable[8]['cost'];
    echo "</td>\r\n\t\t\t<td class=\"act\">";
    if($this->data['club']==0){
    echo $this->getPlusAction( 8 );
    }else {
    echo ACTIVED;
    }
    echo "</td>\r\n\t\t</tr>\t\r\n\t</tbody>\r\n</table>\r\n";    
    
}
else if ( $this->selectedTabIndex == 3 )
{



require_once( LANG_UI_PATH."invit.php" );

include('app/model/colbon.php');

$db_connect = mysql_connect($AppConfig['db']['host'],$AppConfig['db']['user'],$AppConfig['db']['password']);
mysql_select_db($AppConfig['db']['database'], $db_connect);

$Bounusref=($AppConfig['Game']['invitgold']);
$total_people=($AppConfig['Game']['invitpeople']);


?>


<br><br>
<font color=#fc9005 size=4><b><?php echo LANGUI_INVIT_1; ?></b></font><br>

<br><br><hr>


    
        
<?php
echo "</p> \r\n<form method=\"post\" action=\"plus.php?t=3\"> \r\n<table cellpadding=\"1\" cellspacing=\"1\" id=\"sign_input\"> \r\n\t<tbody> \r\n\t\t<tr class=\"top\"> \r\n\t\t\t";


$Tak=$this->player->playerId;

$Samadi=explode('plus.php',$_SERVER['REQUEST_URI']);
$Link="http://".$_SERVER['HTTP_HOST'].$Samadi[0]."register.php?reff=".$Tak;


echo "<span class=\"notice\">";

echo LANGUI_INVIT_2;
echo"</span><p><center><span class=\"link\">";
echo "<a href=\"register.php?uid=";
		echo $this->player->playerId;
		echo "\">";
		echo $Link;
		echo "</a></span>";

		

echo"</center>";
echo "<br><hr><br>";
    $result = mysql_query("SELECT * FROM p_players WHERE id='$Tak'");
	if(isset($result)){
    $i=0;
    while($row = mysql_fetch_array($result)){
    $i++;    
	$wrongpass=0;
    $id = $row['id'];
	$name = $row['name'];
	

			
			$result2 = mysql_query("SELECT * FROM p_refrence WHERE player_name='$name' && Goldsend=0");
			if(isset($result2)){
				$l=0;		
				while($row = mysql_fetch_array($result2)){
					$player_idx[$l]= $row['player_id'];
					$l++;
				}
			}


	

}

$total_people_counter=0;
$Ls=0;
//SEC
if($i>0){
	

		


	for($j=0;$j<$l;$j++){

	$player_ids=$player_idx[$j];
		$result3 = mysql_query("SELECT * FROM p_players WHERE id='$player_ids'  ORDER BY total_people_count ");

			if(isset($result3)){
				$k=0;		
				while($row = mysql_fetch_array($result3)){
					$total_people_countx[$j] = $row['total_people_count'];
					if($total_people_countx[$j]>$total_people_counter){
					$total_people_counter=$row['total_people_count'];
					$Ls=$j;
					}
						$player_idx[$j] = $row['id'];
						$player_namex[$j] = $row['name'];
						
						$villages_countx[$j] = $row['villages_count'];
				
					$k++;
				}
			}
			
	echo "<p>";	 
	}


	echo "<table id=\"plusFunctions\" cellpadding=\"1\" cellspacing=\"1\"><thead><tr><th colspan=\"6\">";
	echo INVITP;
	echo "</th></tr><tr>";
	echo "<td>X</td><td>";
	echo NameR;
	echo "</td><td>";
	echo People;
	echo"</td><td>";
	echo Village;
	echo "</td><td>";
	echo Status;
	echo "</td></tr>";
	if($l>0)
	{
		for ($ii=0;$ii<$j;$ii++){
			echo "<center><p>";

			?>

			<tr class=\"null\">
			<td><center><p><?php echo  ($ii+1); ?></p></center></td>
			<td><center><?php echo " <a href=\"profile.php?uid=";
			echo$player_idx[$ii];
			echo "\">";
			echo $player_namex[$ii];
			echo "</a>"; ?></center></td>
			<td><center><?php echo $total_people_countx[$ii] ?></center></td>
			<td><center><?php echo $villages_countx[$ii] ?></center></td>
			<td><center><?php if(($total_people_countx[$ii]==$total_people_counter) && ($total_people_countx[$ii]>=$total_people) && ($ii==$Ls)) { ?><p class="btn"><center><input type="hidden" value="<?php echo $player_idx[$ii]; ?>" name="submit" /><input type="image" value="1" name="s1" id="btn_ok" class="dynamic_img" src="assets/x.gif" /></center></p></form></center></td>
			<?php }
					elseif(($total_people_countx[$ii]==$total_people_counter) && ($total_people_countx[$ii]>=$total_people))
					{ 
						echo LANGUI_INVIT_4;
					}  
					else 
					{
						echo LANGUI_INVIT_5;
					}
			?>
			</tr>


			<?php

			  

		}
	}
	else{
		echo "<tbody><tr><td class=\"none\" colspan=\"6\">";
		echo LANGUI_INVIT_7;
		echo "</td></tr></tbody>";
	}
	

	if((isset($_POST['submit']))&& (isset($player_idx))){
				


				if (in_array($_POST['submit'], $player_idx)) {
					$Id_player=$_POST['submit'];
				
							mysql_query("UPDATE p_players SET  gold_num = gold_num +'$Bounusref',goldchek = goldchek +'$Bounusref' Where name='$name' ")or die(mysql_error()); 
							mysql_query("UPDATE p_refrence SET  Goldsend =1  WHERE  player_id = '$Id_player' && player_name='$name' ")or die(mysql_error()); 
							echo "<center><font color=#E45D0B size=4><b>";
							echo LANGUI_INVIT_6;
							echo "</b> </font></b></center>";	


							
							
				}
			}
	

	echo "</thead></table>";

}
if($i==0){
     echo "<center><font color=#F80712 size=4><b>";
	 echo LANGUI_INVIT_8;
	 echo "</b> </font></b></center>";	
}

}

?>
	<br><p><hr><br><form action="<?php

 echo $_SERVER['PHP_SELF'];

?>?s" method="post">
<center> 
    <tbody>
		
		<td><font color=#BB47BF><b><?php echo EmailFr; ?></b></font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input class="text" name="email" value="" maxlength="50" type="email"></td></tr>
		<tr class=\"null\"><p>
		<td><font color=#BB47BF><b><?php echo EmailText; ?></b></font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<textarea name="sendsms" cols="50" rows="3" ></textarea></td>
  		<tr class=\"null\"><p>
  	 </tbody>

<p class="btn"><center><input type="hidden" value="5" name="submit5" /><input type="image" value="1" name="s1" id="btn_ok" class="dynamic_img" src="assets/x.gif" />

    
    </form>
</hr>	
<?php
 if(isset($_POST['submit5'])) {
 
	 $Taki=$this->player->playerId;

	$Samadii=explode('plus.php',$_SERVER['REQUEST_URI']);
	$Linki="http://".$_SERVER['HTTP_HOST'].$Samadii[0]."register.php?reff=".$Taki;


			
 	$email = $_POST['email'];
	$sendsms = $_POST['sendsms']          .$Linki;

	if ($email===''){
		echo "<center><font color=red>";
		echo Emailerr;
		echo "</font></center>";
	}
	elseif ($_POST['sendsms']===''){
		echo "<center><font color=red>";
		echo SMSerr;
		echo "</font></center>";
		echo '<p align="center"><font color=#1E74B0 size="3">';
		Echo No_send;
		echo "</font></p>";

	}
	elseif(($_POST['sendsms']!='')&&($email!='')) {

		$subject = LANGUI_INVIT_9;
		$to=$email;
		$headers=$Linki;
		
		mail($to,$subject,$sendsms,$headers);
		
		echo '<p align="center"><font color=#1E74B0 size="3">';
		Echo OK_send;
		echo "</font></p>";
	}
}




}
else if ( $this->selectedTabIndex == 4 )
{
	$resu=mysql_query("SELECT * FROM g_gold ", $conn );   
	$row = mysql_fetch_assoc($resu); 
	$lock6=$row['lock6'];
	$gold_copoun=$row['gold_copoun'];
	if($lock6!=0)
	{
		echo "<hr><p><center><font color=red size=3><b>";
		echo Lock6;
		echo "</b></font></center><hr>";
	}
	if($lock6==0)
	{
		echo "<p><br><center>";
		echo $GOLDEX;
		?>
		<img src="assets/x.gif" class="gold" alt="<?php echo LANGUI_PLUS_T6; ?>" title="<?php echo LANGUI_PLUS_T6; ?>"><p><br>
		<?php 

		 echo "<table id=\"plusFunctions\" cellpadding=\"1\" cellspacing=\"1\"><thead><tr><th colspan=\"6\">";
		 echo LANGUI_PLUS_T60; echo "&nbsp;&nbsp;&nbsp;&nbsp;"; echo $percent; echo "%"; 
		 echo "</th></thead></tr></table>";
		 
		 ?>
		 
		</center>
		<p><br><p>
		<form action="<?php echo $_SERVER['PHP_SELF'];?>?t=4" method="post">
			 <center> 
				<tbody>
					<td><font color=#040404><b> <?php echo LANGUI_PLUS_T50; ?> :  &nbsp;&nbsp;&nbsp;</b></font><input class="iInput" name="active" value="" maxlength="50" type="text"></td>
				</tbody>
			</center>
			  <p><br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

			 <p class="btn"><center><input type="hidden" value="5" name="submit1" /><input type="image" value="1" name="s1" id="btn_ok" class="dynamic_img" src="assets/x.gif" />

		</form>
			</p></br>
			
				
		<?php
		 if(isset($_POST['submit1'])) {

			$Golderi=trim($_POST['active']);
			$Golder=intval(preg_replace("/[^0-9]/","",$Golderi));
			if(empty($Golder)){
				echo "<p><center><font color=red><b>";
				echo LANGUI_PLUS_T53;
				echo "</font>";
			}
			elseif($Golder<$gold_copoun){
				echo "<p><center><font color=red><b>";
				echo LANGUI_PLUS_goldfew;
				echo "</font>";
				echo $gold_copoun;
				echo "<img src=\"assets/x.gif\" class=\"gold\">";
				echo "<font color=red>";
				echo LANGUI_PLUS_goldfew2;
				echo "</font>";	
			}
			else{
				$preg_match=preg_match( "/[:,\\. ^? * ! @ # % ^ & * +   - a b c d e f g h i j k l m n o p q r s t u w x y z A B C D E F G H I J K L M N O P Q R S T U W X V Y Z < > \\n\\r\\t\\s]+/", $Golder );
				if ($preg_match != 0 )
				{
					echo "<p><center><font color=red><b>";
					echo LANGUI_PLUS_T51;
					echo "</font>";
				}
				elseif($Golder<0){
					echo "<p><center><font color=red><b>";
					echo LANGUI_PLUS_T51;
					echo "</font>";		
				}
				
				elseif($preg_match==0 && $Golder>0)
				{
				$GOLDEND=($GOLDEX-(($GOLDEX/100)*$percent));
					if($Golder>$GOLDEND){
						echo "<p><center><font color=red><b>";
						echo LANGUI_PLUS_T52;
						echo "</font>";
					}
					if($GOLDEND>=$Golder){
						$username=$this->data['name'];
						$GOLDE=$Golder+(($Golder/100)*$percent);
						echo "<p><center><font color=green><b>";
						echo  Your_Coupon;
						echo "</font>";
						echo $R = substr(str_shuffle(str_repeat("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",12)),0,12);
						echo "<br /><font color=green>";
						echo Warning_Coupon;
						echo "</font></b></center>";
						mysql_query("INSERT INTO `bank` (`code`, `value`, `password`, `playersave`) VALUES('$R', '$Golder', '5', '$username')", $conn2)or die(mysql_error());
						mysql_query("UPDATE p_players set gold_num=gold_num-'$GOLDE',goldchek = goldchek -'$GOLDE' where id='$Tak'",$conn) or die(mysql_error());
						$subject="Your Coupon code : Travonline.net";
						$headers="";
						$sendsms=$R;
						mail($emailer,$subject,$sendsms,$headers);

					}
				}	
			}
		}		
			
	}

}

else if ( $this->selectedTabIndex == 5 )
{
	$resu=mysql_query("SELECT * FROM g_gold ", $conn );   
	$row = mysql_fetch_assoc($resu); 
	$lock7=$row['lock6'];
	if($lock7!=0)
	{
		echo "<hr><p><center><font color=red size=3><b>";
		echo Lock6;
		echo "</b></font></center><hr>";
	}
	if($lock7==0)
	{
	
		echo "<p><br><center>";
		echo $GOLDEX;
		?>
		<img src="assets/x.gif" class="gold" alt="<?php echo LANGUI_PLUS_T6; ?>" title="<?php echo LANGUI_PLUS_T6; ?>"></center><p><br>
		<form action="<?php echo $_SERVER['PHP_SELF'];?>?t=5" method="post">
			 <center> 
				<tbody>
					<br><td><font color=#040404><b>  <?php echo LANGUI_PLUS_T54; ?>  :  &nbsp;&nbsp;&nbsp;</b></font><input class="iInput" name="givecode" value="" maxlength="50" type="text"></td>
				</tbody>
			</center>
			  <p><br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

			 <p class="btn"><center><input type="hidden" value="5" name="submit2" /><input type="image" value="1" name="s1" id="btn_ok" class="dynamic_img" src="assets/x.gif" />

		</form>
			</p></br>
			
				
		<?php
		 if(isset($_POST['submit2'])) {

			$Goldgive=trim($_POST['givecode']);

			if(empty($Goldgive)){
				echo "<p><center><font color=red><b>";
				echo LANGUI_PLUS_T55;
				echo "</font>";
			}
			else{
				$res=mysql_query("SELECT * FROM bank where code='$Goldgive' and getgold='0' ", $conn2) or die(mysql_error()); 
				$row = mysql_fetch_assoc($res); 
				$Vcode=$row['value'];
				$Pcode=$row['code'];
				
				
				if(isset($Vcode)){
					$username=$this->data['name'];
					mysql_query("UPDATE p_players set gold_num=gold_num+'$Vcode',goldchek = goldchek+'$Vcode'  where id='$Tak'",$conn) or die(mysql_error());
					mysql_query("UPDATE `bank` set getgold=1,playeruse='$username' WHERE code = '$Pcode' ",$conn2) or die(mysql_error());
					echo "<p><center><font color=green><b>";
					echo LANGUI_PLUS_T56;
					echo "</font>";
				}
				else{
					echo "<p><center><font color=red><b>";
					echo LANGUI_PLUS_T57;
					echo "</font>";

				}
			
					
			}
		}


	}
}

else if ( $this->selectedTabIndex == 6 )
{
$Taghsim=150;

		echo "<p><br><table class=\"product lang_rtl lang_ar\" cellpadding=\"1\" cellspacing=\"1\">\r\n\t\t<thead>\r\n\t\t\t<tr><th><center>";
		echo $GOLDEX;

		?>
		<img src="assets/x.gif" class="gold" alt="<?php echo LANGUI_PLUS_T6; ?>" title="<?php echo LANGUI_PLUS_T6; ?>">
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<?php echo $SilverX; ?>
		<img src="assets/default/img/a/silver.gif" alt="<?php echo LANGUI_PLUS_T6; ?>" title="<?php echo LANGUI_PLUS_T6; ?>">
		<br><br><p><p>
		<font size=3 color=#000><b> <?php echo LANGUI_PLUS_T61;  echo "&nbsp;<font size=3 color=orange>"; echo $Taghsim;  echo "</font>&nbsp;"; echo LANGUI_PLUS_T62; echo "</b></font>"; ?>
		</center></th></thead></table><p><br>
		<form action="<?php echo $_SERVER['PHP_SELF'];?>?t=6" method="post">
			 <center> 
				<tbody>
					<br><td><font color=#040404><b>  <?php echo LANGUI_PLUS_T65; ?>  :  &nbsp;&nbsp;&nbsp;</b></font><input class="iInput" name="givesilver" value="" maxlength="50" type="text"></td>
				</tbody>
			</center>
			  <p><br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

			 <p class="btn"><center><input type="hidden" value="5" name="submit3" /><input type="image" value="1" name="s1" id="btn_ok" class="dynamic_img" src="assets/x.gif" />

		</form>
			</p></br>
			
				
		<?php
		 if(isset($_POST['submit3'])) {

			$Silvergive=trim($_POST['givesilver']);
			$Silveri=intval(preg_replace("/[^0-9]/","",$Silvergive));
			if(empty($Silvergive)){
				echo "<p><center><font color=red><b>";
				echo LANGUI_PLUS_T55;
				echo "</font>";
			}
			else{

				
				
				if((isset($Silveri))){
					if($SilverX>=$Silveri)
					{
						if($Taghsim<=$Silveri){
							$Silvero=($Silveri/$Taghsim);
						
							mysql_query("UPDATE p_players set gold_num=gold_num+'$Silvero',silver = silver - '$Silveri'  where id='$Tak'",$conn) or die(mysql_error());
							echo "<p><center><font color=green><b>";
							echo LANGUI_PLUS_T56;
							echo "</font>";
						}
						else{
							echo "<p><center><font color=red><b>";
							echo LANGUI_PLUS_T63;
							echo "</font>";
						
						}
						
					}
					else{
						echo "<p><center><font color=red><b>";
						echo LANGUI_PLUS_T64;
						echo "</font>";
					}
					
				}
				else{
					echo "<p><center><font color=red><b>";
					echo LANGUI_PLUS_T57;
					echo "</font>";

				}
			
					
			}
		}



	
}
?>
